### ISSUE TITLE
Invalid download URLs

### ISSUE THREAD

**Issue by Duzij** [UgoLomoio/ECG_DSS_CAE#1]
Hello,
I would like to check out the project.
Sadly both download links [seem expired](https://github.com/UgoLomoio/ECG_DSS_CAE/blob/617fdf2545465a5b208ba314864220eefbbd1f39/EcgStuffs/README.md?plain=1#L11C1-L11C1
). 
Could you please update those?

**Comment by UgoLomoio** [comment]
Hello,

The README file in the ECGStuffs repository was an old one, now is deleted.

You can find and download the dataset used to train and test the model here: https://physionet.org/content/ptbdb/1.0.0/
If needed, we can provide training and test split used. 

For the trained model, you can access it directly from the github repository (is the one under the name "model.pt")
